FROM node:19-alpine

WORKDIR /app

ENV NEXT_PUBLIC_SANITY_PROJECT_ID="rs8pzjyh"
ENV NEXT_PUBLIC_SANITY_DATASET="production"
ENV NEXT_PUBLIC_SANITY_API_VERSION="2022-11-15"
ENV SANITY_API_READ_TOKEN="skFTfcZ4v7Rbs9rKTx7EencqisyPkmgGlIFIuaydYBsuTeYHxAZ4IdAx9T4zgTAU7fpXjPbWlOHbzC1LMsNmHgSbpNzby0Li4zxC6KbS41nlgymzK4nLdCezWdT4lJYoyRSORrzWCgMq4dssCB5nGwpWC8SzOv7B7GR4gI46IK8wwNmRPYN6"

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

EXPOSE 3000

CMD yarn run dev
